CREATE TABLE [dbo].[Task]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Note] NVARCHAR(1500),
	[UserID] INT NOT NULL,
	[SprintID] INT NOT NULL,

	CONSTRAINT [FK_dbo.Task_dbo.Task_SprintID] FOREIGN KEY ([SprintID]) REFERENCES [dbo].[Sprint] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_dbo.Task_dbo.Task_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE
)
